"""Add nullable media columns to complaints table

Revision ID: 355f24925846
Revises: 
Create Date: 2025-05-12 17:42:07.767689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '355f24925846'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Try to drop the temporary table if it exists
    try:
        op.drop_table('_alembic_tmp_complaints')
    except OperationalError:
        pass
    
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        # Add new columns
        batch_op.add_column(sa.Column('media_path', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('media_type', sa.String(length=10), nullable=True))
        
        # Update latitude and longitude to non-nullable
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=False)
        
        # Try to drop image_path if it exists
        try:
            batch_op.drop_column('image_path')
        except OperationalError:
            pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=256), nullable=True))
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_column('media_type')
        batch_op.drop_column('media_path')

    # Don't create _alembic_tmp_complaints in downgrade
    # ### end Alembic commands ###
